#!/usr/bin/env python3
"""
Unique + exclusive ligand selection ("primera selección" in the thesis).

Step 1: from the enriched candidate list, keep OG7 groups where every
crystallized structure is bound to exactly the same single ligand.

Step 2: of those, keep only the groups whose ligand does NOT appear in
any other OG7 group across all of BioLiP -- i.e. genuinely exclusive to
that family, not just locally unique within the candidate pool.

From the resulting list, 2 OG7 groups were picked for the PocketVec pilot
round (decanoic acid, 5-O-phosphono-beta-D-arabinofuranose), discarding
candidates with phospholipid/macromolecule-type ligands, crystallization
artifacts, or no assigned EC number (manual curation step, not scripted).

Note: the original version of step 2 read its candidate list from a
Tanimoto-clustering table generated by a separate, unversioned analysis.
Here it instead reads directly from step 1's output, which keeps the same
logic without that broken dependency.
"""
import gzip
from pathlib import Path

import pandas as pd

IN_DIR = "biolip_exploracion"
OUT_DIR = "biolip_exploracion2"
LIGAND_FILE = "ligand.tsv.gz"

COLS_BIOLIP = [
    "pdb_id", "chain", "resolution", "binding_site",
    "ligand_id", "ligand_chain", "ligand_serial",
    "binding_residues_pdb", "binding_residues_renum",
    "catalytic_pdb", "catalytic_renum",
    "ec_number", "go_terms",
    "affinity_manual", "affinity_moad", "affinity_pdbbind", "affinity_bindingdb",
    "uniprot_id", "pubmed_id", "ligand_seqnum", "receptor_seq",
]
LIGANDS_EXCLUDE = {
    "HOH", "DOD", "WAT", "SO4", "PO4", "GOL", "EDO", "PEG", "BME",
    "ACT", "ACE", "FMT", "MPD", "MES", "TAR", "CIT", "TRS", "EPE",
    "MG", "ZN", "CA", "FE", "MN", "NA", "K", "CL", "CU", "NI", "CO",
    "SE", "CD", "HG", "PT", "AU", "AG", "IOD", "BR", "ION", "FLC", "DMS",
}

SEQS_DIR      = "/home/ssneider/disco-big/ssneider-env/TDR_Targets7.1/actualizados_short/sequences"
MAPPER_DIR    = "/home/ssneider/disco-big/ssneider-env/TDR_Targets7.1/gene_mapper/Ortho_vs_Uniprot"
NOT_ORTHO_DIR = "/big/lab/mercedesdg/TDR_Targets_7/OrthoMCL/genomes_v7/not_on_orthomcl/new_genomes"
SPECIES_UNIPROT_DIRECT  = {"atha", "dmel", "osat", "cele", "ddis", "ecol", "mtub"}
SPECIES_NOT_ON_ORTHOMCL = {"ovo", "egr", "kpm", "loa", "sao"}
ORTHO_FILE_NAMES = {"egr": "egr_OrthoMCL_asignation_evaluation.tsv"}


def load_ligand_names():
    cols = ["lig_id", "formula", "inchi", "inchikey", "smiles", "name", "chebi", "drugbank", "zinc"]
    with gzip.open(LIGAND_FILE, "rt", encoding="utf-8", errors="replace") as f:
        df_lig = pd.read_csv(f, sep="\t", header=None, names=cols, on_bad_lines="warn", engine="python")
    df_lig["lig_id"] = df_lig["lig_id"].astype(str).str.strip().str.upper()
    df_lig["short_name"] = df_lig["name"].astype(str).str.split(";").str[0].str.strip()
    return dict(zip(df_lig["lig_id"], df_lig["short_name"]))


def step1_unique_ligand(lig_names):
    """Groups with exactly one distinct crystallized ligand."""
    df_final = pd.read_csv(f"{OUT_DIR}/candidatos_final.tsv", sep="\t")
    print(f"Candidates loaded: {len(df_final):,}")

    df_unique = df_final[df_final["n_ligandos_unicos"] == 1].copy()
    df_unique["ligando_unico"] = df_unique["top_ligandos"].astype(str).str.split(",").str[0].str.strip()
    df_unique["nombre_ligando_unico"] = df_unique["ligando_unico"].map(lig_names).fillna(df_unique["ligando_unico"])
    df_unique = df_unique.sort_values(["n_especies_red", "n_uniprot_biolip"], ascending=False).reset_index(drop=True)

    cols = ["og7", "n_especies_red", "n_prot_red", "n_especies_biolip",
            "n_uniprot_biolip", "resolucion_media", "ligando_unico", "nombre_ligando_unico",
            "ec_numbers", "especies_red", "especies_biolip"]

    print(f"\nTotal OG7 groups with a single crystallized ligand: {len(df_unique):,}")
    print(df_unique[cols].to_string(index=False))

    df_unique[cols].to_csv(f"{OUT_DIR}/og7_ligando_unico.tsv", sep="\t", index=False)
    print(f"\nSaved: {OUT_DIR}/og7_ligando_unico.tsv")
    return df_unique[cols]


def build_uniprot_to_og7(og7_set):
    """Same three-path ID resolution used across the project, restricted to
    the OG7 groups of interest to keep this step fast."""
    uniprot_to_og = {}
    mapper_path = Path(MAPPER_DIR)
    all_mapper_species = {p.name for p in mapper_path.iterdir() if p.is_dir()}
    species_mapper = all_mapper_species - SPECIES_UNIPROT_DIRECT - SPECIES_NOT_ON_ORTHOMCL
    if "tcr" in species_mapper:
        species_mapper.discard("tcr")
        species_mapper.add("tcru")

    for species in SPECIES_UNIPROT_DIRECT:
        for pat in [f"{species}_aa_seqs_OrthoMCL-7.fasta", f"{species}_protein.fasta"]:
            fp = Path(SEQS_DIR) / pat
            if fp.exists():
                with open(fp) as f:
                    for line in f:
                        if line.startswith(">"):
                            parts = line.strip().lstrip(">").split()
                            if len(parts) >= 2:
                                uid = parts[0].split("|")[1] if "|" in parts[0] else parts[0]
                                og = next((p for p in parts if p.startswith("OG7_")), None)
                                if og and og in og7_set:
                                    uniprot_to_og[uid] = og
                break

    for species in sorted(species_mapper):
        ed = "tcru" if species == "tcru" else species
        mf = mapper_path / ed / "mapped_clean.csv"
        if not mf.exists():
            mf = mapper_path / "tcr" / "mapped_clean.csv"
        if not mf.exists():
            continue
        dm = pd.read_csv(mf, dtype=str)
        n2u = dict(zip(dm["OrthoMCL_ID"].str.strip(), dm["Uniprot_ID"].str.strip()))
        for pat in [f"{species}_aa_seqs_OrthoMCL-7.fasta", f"{species}_protein.fasta"]:
            fp = Path(SEQS_DIR) / pat
            if fp.exists():
                with open(fp) as f:
                    for line in f:
                        if line.startswith(">"):
                            parts = line.strip().lstrip(">").split()
                            if len(parts) >= 2:
                                nid = parts[0].split("|")[1] if "|" in parts[0] else parts[0]
                                og = next((p for p in parts if p.startswith("OG7_")), None)
                                uid = n2u.get(nid)
                                if og and uid and og in og7_set:
                                    uniprot_to_og[uid] = og
                break

    for species in sorted(SPECIES_NOT_ON_ORTHOMCL):
        nb = ORTHO_FILE_NAMES.get(species, f"{species}_orthomcl7.1.txt")
        of = Path(NOT_ORTHO_DIR) / species / nb
        mf = mapper_path / species / "mapped_clean.csv"
        if not of.exists() or not mf.exists():
            continue
        dm = pd.read_csv(mf, dtype=str)
        n2u = dict(zip(dm["OrthoMCL_ID"].str.strip(), dm["Uniprot_ID"].str.strip()))
        do = pd.read_csv(of, sep="\t", dtype=str)
        do.columns = do.columns.str.strip()
        for _, row in do.iterrows():
            qid = str(row[do.columns[0]]).strip()
            og = str(row[do.columns[2]]).strip()
            if not og.startswith("OG7_") or og not in og7_set:
                continue
            nid = qid.split("|")[1] if "|" in qid else qid
            uid = n2u.get(nid)
            if uid:
                uniprot_to_og[uid] = og

    return uniprot_to_og


def step2_exclusive_ligand(df_unique, lig_names):
    """Of the unique-ligand groups, keep only those whose ligand doesn't
    appear in any other OG7 group in all of BioLiP."""
    og7_set = set(df_unique["og7"])

    with gzip.open("BioLiP.txt.gz", "rt", encoding="utf-8", errors="replace") as f:
        df_bio = pd.read_csv(f, sep="\t", header=None, names=COLS_BIOLIP, low_memory=False)

    df_bio["resolution"] = pd.to_numeric(df_bio["resolution"], errors="coerce")
    df_bio["uniprot_first"] = df_bio["uniprot_id"].astype(str).str.split(",").str[0].str.strip()
    df_bio["has_uniprot"] = df_bio["uniprot_first"].str.match(r"^[A-Z][0-9][A-Z0-9]{3}[0-9]$")
    df_bio["ligand_id"] = df_bio["ligand_id"].astype(str).str.strip().str.upper()
    df_bio["ligand_bio"] = ~df_bio["ligand_id"].isin(LIGANDS_EXCLUDE)
    df_bio_clean = df_bio[(df_bio["resolution"] > 0) & df_bio["has_uniprot"] & df_bio["ligand_bio"]].copy()

    uniprot_to_og = build_uniprot_to_og7(og7_set)
    df_bio_clean["og7"] = df_bio_clean["uniprot_first"].map(uniprot_to_og)
    df_with_og = df_bio_clean[df_bio_clean["og7"].notna()].copy()
    print(f"BioLiP entries cross-referenced with OG7: {len(df_with_og):,}")

    # How many distinct OG7 groups each ligand appears in, across all of BioLiP
    lig_to_n_og7 = df_with_og.groupby("ligand_id")["og7"].nunique()

    df_unique["og7_count_for_ligand"] = df_unique["ligando_unico"].map(lig_to_n_og7)
    df_exclusive = df_unique[df_unique["og7_count_for_ligand"] == 1].copy()
    df_exclusive = df_exclusive.sort_values(["n_especies_red", "n_uniprot_biolip"], ascending=False)

    print(f"\nOG7 groups with a ligand unique AND exclusive to that family: {len(df_exclusive):,}")
    print(df_exclusive.to_string(index=False))

    df_exclusive.to_csv(f"{OUT_DIR}/og7_ligando_unico_exclusivo.tsv", sep="\t", index=False)
    print(f"\nSaved: {OUT_DIR}/og7_ligando_unico_exclusivo.tsv")
    return df_exclusive


def main():
    lig_names = load_ligand_names()
    df_unique = step1_unique_ligand(lig_names)
    step2_exclusive_ligand(df_unique, lig_names)


if __name__ == "__main__":
    main()
