# Segunda selección — PocketVec Stage 2 (3 finalist OG7 groups)

Second, more careful PocketVec round: 3 finalist OG7 groups selected by
pocket sequence divergence, run with better-constructed receptors and
all-against-all structural alignment instead of a single fixed anchor.

## Pipeline, in order

| # | Script | What it does | Manuscript section |
|---|---|---|---|
| 01 | `01_candidate_filter_247.py` | Ligand categorization (KEGG/DrugCentral/RDKit) + lineage-based filter | 992 → 247 groups |
| 02 | `02_sequence_divergence_mafft.py` | MAFFT-based pocket divergence scoring vs. a null distribution | 247 → 3 finalists (OG7_0000433/ADP, OG7_0001020/RAP, OG7_0006854/FMN) |
| 03 | `03_centroid_and_usalign_dynamic_anchor.py` | Reference centroids on crystal structures + all-vs-all US-align, best-TM-score anchor per species | "Corrida de PocketVec" (segunda ronda) |
| 04 | `04_receptor_prep_and_pocketvec_run.py` | Receptor cleanup/MOL2 conversion, centroid `.sd` files, the crystal→AlphaFold flat-descriptor fix, and the final n_runs=25 docking run | "PocketVec: ¿estructura cristalográfica o predicha?" |
| 05 | `05_pocketvec_comparison_stage2.py` | Final intra-/inter-OG7 similarity comparison | Tabla 4, Figura 21 |
| 06 | `06_fmn_protein_interactions.py` | Raw-distance + PLIP contact analysis, cross-species comparison via BLOSUM62 alignment | "Interacciones proteína–FMN", Tabla 5 |

## Notes on this version

- This consolidates three heavily iterative working notebooks
  (`filtrar_candidatos.ipynb`, `testeo_y_corrida_completa_pocketvec.ipynb`,
  `analisis_global_2.ipynb`, `analisis_global_3.ipynb`) into a linear
  pipeline. Left out: one-off manual patches that don't reflect the
  general method (a single species' paralog swapped by hand, several
  `TEST`/`CHECK`/`v2`/`v3` retries of the same step, individually
  hardcoded UniProt ID corrections). The **outcome** of those fixes
  (e.g. which 5 species needed the AlphaFold-receptor substitution) is
  documented and reproduced in script 04, since it's a real, reported
  finding — not debugging noise.
- `01_candidate_filter_247.py` originally read from a
  `candidatos_con_clusters.tsv` table generated by an unversioned
  Tanimoto-clustering analysis (same gap noted in the Primera selección
  README). Here it reads from `candidatos_final.tsv` (output of
  `04_candidate_enrichment.py` in the Primera etapa) instead; the
  ligand-cluster count column isn't reproduced, since it wasn't used by
  the filter logic itself.
- `03_centroid_and_usalign_dynamic_anchor.py`'s per-species reference
  PDB IDs/chains and UniProt IDs are the fixed outcome of the earlier
  selection and lookup steps (BioLiP + Gene Mapper), not something this
  script derives on its own — they're listed directly in `GRUPOS`.
- ChimeraX is used only to render the interaction figure in the thesis;
  it isn't part of the analysis and isn't reproduced in
  `06_fmn_protein_interactions.py`.

## Dependencies not included

`GeneMapper`, US-align, PocketVec, PLIP, and OpenBabel are external tools
run as subprocesses / via their own protocols, not included here.
