# 06 — PocketVec / US-align structural pocket validation (Stage 1)

Validates predicted binding pockets across species by transferring a
reference pocket's centroid, via structural alignment, from a
crystallized species to AlphaFold models of the other species, then
comparing pocket descriptors (PocketVec) between them. This covers
Objective 5 of the thesis, "Primera etapa" (2 pilot OG7 groups).

The second stage (3 finalist OG7 groups selected by pocket sequence
divergence, plus the FMN interaction analysis) will be added separately.

## Pipeline, in order

| # | Script | What it does | Manuscript section |
|---|---|---|---|
| 01 | `01_biolip_og7_crossreference.py` | Cross-references BioLiP with the network's OG7 orthology groups | "Selección de candidatos: filtrado inicial" (4,131 groups with a BioLiP structure) |
| 02 | `02_candidate_filter_initial.py` | Filters by resolution, ligand type, and species count (own-crystal count) | "Filtrado inicial" (131 groups) |
| 03 | `03_candidate_filter_corrected_coverage.py` | Corrects the species count to the full network (not just species with their own crystal) | "Segunda selección" (131 → 992 groups) |
| 04 | `04_candidate_enrichment.py` | Enriches the 992 candidates with ligand names and overview figures | "Segunda selección" |
| 05 | `05_unique_exclusive_ligand_selection.py` | Filters to a single crystallized ligand, then to ligands exclusive to that OG7 group | "Primera selección" (2 pilot groups: decanoic acid, arabinofuranose-P) |
| 06 | `06_pocket_centroid_reference.py` | Computes the reference pocket centroid on the crystallographic structure | "Corrida de PocketVec" |
| 07 | `07_usalign_centroid_transfer.py` | Transfers the centroid to each species' AlphaFold model via US-align | "Corrida de PocketVec" |
| 08 | `08_pocket_plddt.py` | Whole-protein and pocket-region (8 Å radius) pLDDT | "Corrida de PocketVec" |
| 09 | `09_pocketvec_comparison_stage1.py` | Runs the final intra-/inter-OG7 descriptor comparison | "Primera etapa" (results) |

## Notes on this version

- Excludes an earlier exploratory pass over BioLiP grouped by EC
  (enzyme class) rather than by OG7 (orthology group); that path
  wasn't the one used for the thesis results.
- `05_unique_exclusive_ligand_selection.py`'s second step originally read
  from a Tanimoto-clustering table that isn't part of this pipeline
  (generated by a separate, unversioned chemical-clustering analysis).
  Here it reads directly from the first step's output instead, keeping
  the same exclusivity logic without that dependency.
- `06_pocket_centroid_reference.py` merges what were two separate,
  partly duplicated notebooks (reference-structure lookup and centroid
  calculation) into one script, using the parsed binding-site residues
  directly instead of a second, hand-copied residue list.
- Several downstream candidate-selection plots (chemical diversity by
  Tanimoto clusters, "most studied" OG7 ranking) were left out: they
  were exploratory and aren't referenced in the thesis text.

## Dependencies not included

`GeneMapper` (used indirectly via `mapped_clean.csv`) is a lab tool
already cited in the thesis and covered in `04_gene_mapper/`. US-align
and PocketVec itself are external tools, run as subprocesses / via their
own protocol, not included here.
